### ISSUE TITLE
module fails on asyncIterator polyfill

### ISSUE THREAD

**Issue by shaikatz** [jcormont/documentdb-typescript#12]
Hi,

Getting this error when trying to use the Collection object:

`babel-node app.js --presets es2015
/Users/shai/Development/***/src/node_modules/documentdb-typescript/dist/DocumentStream.js
:13
Symbol.asyncIterator = Symbol.asyncIterator || Symbol("Symbol.asyncIterator");
TypeError: Cannot assign to read only property 'asyncIterator' of function 'function Symbol()
{ [native code] }'
    at Object.<anonymous> (/Users/shai/Development/***/src/node_modules/documentdb-typesc
ript/dist/DocumentStream.js:13:22)
    at Module._compile (module.js:571:32)
    at Module._extensions..js (module.js:580:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/shai/Development/***/src/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/shai/Development/***/src/node_modules/documentdb-typesc
ript/dist/Collection.js:12:26)`

Putting the following line guarded by `if (!Symbol.asyncIterator)` fixed the issue for me.
`Symbol.asyncIterator = Symbol.asyncIterator || Symbol("Symbol.asyncIterator");`

**Comment by jcormont** [comment]
Thanks! Merged your PR and this is fixed now in v1.0.6.
